// Code generated by protoc-gen-go. DO NOT EDIT.
// source: donech/erp/v1/erp_api.proto

package erpv1

import (
	context "context"
	fmt "fmt"
	v1 "github.com/donech/donech-/gen/go/donech/util/v1"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//GetSupplierListRequest.
type GetSupplierListRequest struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pager                *v1.Pager `protobuf:"bytes,2,opt,name=pager,proto3" json:"pager,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetSupplierListRequest) Reset()         { *m = GetSupplierListRequest{} }
func (m *GetSupplierListRequest) String() string { return proto.CompactTextString(m) }
func (*GetSupplierListRequest) ProtoMessage()    {}
func (*GetSupplierListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_956871151ebb4d7f, []int{0}
}

func (m *GetSupplierListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSupplierListRequest.Unmarshal(m, b)
}
func (m *GetSupplierListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSupplierListRequest.Marshal(b, m, deterministic)
}
func (m *GetSupplierListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSupplierListRequest.Merge(m, src)
}
func (m *GetSupplierListRequest) XXX_Size() int {
	return xxx_messageInfo_GetSupplierListRequest.Size(m)
}
func (m *GetSupplierListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSupplierListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSupplierListRequest proto.InternalMessageInfo

func (m *GetSupplierListRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetSupplierListRequest) GetPager() *v1.Pager {
	if m != nil {
		return m.Pager
	}
	return nil
}

//GetSupplierListResponse.
type GetSupplierListResponse struct {
	Code                 int32                         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string                        `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *GetSupplierListResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *GetSupplierListResponse) Reset()         { *m = GetSupplierListResponse{} }
func (m *GetSupplierListResponse) String() string { return proto.CompactTextString(m) }
func (*GetSupplierListResponse) ProtoMessage()    {}
func (*GetSupplierListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_956871151ebb4d7f, []int{1}
}

func (m *GetSupplierListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSupplierListResponse.Unmarshal(m, b)
}
func (m *GetSupplierListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSupplierListResponse.Marshal(b, m, deterministic)
}
func (m *GetSupplierListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSupplierListResponse.Merge(m, src)
}
func (m *GetSupplierListResponse) XXX_Size() int {
	return xxx_messageInfo_GetSupplierListResponse.Size(m)
}
func (m *GetSupplierListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSupplierListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSupplierListResponse proto.InternalMessageInfo

func (m *GetSupplierListResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetSupplierListResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetSupplierListResponse) GetData() *GetSupplierListResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

//Data.
type GetSupplierListResponse_Data struct {
	List                 []*Supplier `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Pager                *v1.Pager   `protobuf:"bytes,2,opt,name=pager,proto3" json:"pager,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetSupplierListResponse_Data) Reset()         { *m = GetSupplierListResponse_Data{} }
func (m *GetSupplierListResponse_Data) String() string { return proto.CompactTextString(m) }
func (*GetSupplierListResponse_Data) ProtoMessage()    {}
func (*GetSupplierListResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_956871151ebb4d7f, []int{1, 0}
}

func (m *GetSupplierListResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSupplierListResponse_Data.Unmarshal(m, b)
}
func (m *GetSupplierListResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSupplierListResponse_Data.Marshal(b, m, deterministic)
}
func (m *GetSupplierListResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSupplierListResponse_Data.Merge(m, src)
}
func (m *GetSupplierListResponse_Data) XXX_Size() int {
	return xxx_messageInfo_GetSupplierListResponse_Data.Size(m)
}
func (m *GetSupplierListResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSupplierListResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_GetSupplierListResponse_Data proto.InternalMessageInfo

func (m *GetSupplierListResponse_Data) GetList() []*Supplier {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *GetSupplierListResponse_Data) GetPager() *v1.Pager {
	if m != nil {
		return m.Pager
	}
	return nil
}

func init() {
	proto.RegisterType((*GetSupplierListRequest)(nil), "donech.erp.v1.GetSupplierListRequest")
	proto.RegisterType((*GetSupplierListResponse)(nil), "donech.erp.v1.GetSupplierListResponse")
	proto.RegisterType((*GetSupplierListResponse_Data)(nil), "donech.erp.v1.GetSupplierListResponse.Data")
}

func init() { proto.RegisterFile("donech/erp/v1/erp_api.proto", fileDescriptor_956871151ebb4d7f) }

var fileDescriptor_956871151ebb4d7f = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x6a, 0xdb, 0x30,
	0x18, 0xc7, 0x51, 0xe2, 0x04, 0xa2, 0x10, 0xb6, 0x08, 0x96, 0x78, 0x5e, 0x60, 0xc1, 0xb0, 0x11,
	0x16, 0x90, 0x71, 0x76, 0xda, 0x2e, 0xa5, 0x21, 0xa1, 0x14, 0x7a, 0x30, 0x2e, 0x14, 0x5a, 0x02,
	0xad, 0x9a, 0x08, 0x57, 0x60, 0x5b, 0xaa, 0xa4, 0xf8, 0xd8, 0x43, 0x4f, 0xbd, 0xf7, 0xad, 0x7a,
	0xed, 0x1b, 0x94, 0x3e, 0x48, 0x91, 0xec, 0x1e, 0x92, 0x50, 0xda, 0x9e, 0xf4, 0x99, 0xef, 0xe7,
	0x9f, 0xfe, 0xd2, 0x27, 0xf8, 0x63, 0xc5, 0x73, 0xba, 0xbc, 0x0a, 0xa8, 0x14, 0x41, 0x11, 0x9a,
	0xe5, 0x9c, 0x08, 0x86, 0x85, 0xe4, 0x9a, 0xa3, 0x4e, 0xd9, 0xc4, 0x54, 0x0a, 0x5c, 0x84, 0xde,
	0xcf, 0x5d, 0x36, 0xa3, 0x4a, 0x91, 0x84, 0x96, 0xbc, 0xf7, 0xbd, 0x02, 0xd6, 0x9a, 0xa5, 0x86,
	0x30, 0x6b, 0xd5, 0x1a, 0x24, 0x9c, 0x27, 0x29, 0x0d, 0x88, 0x60, 0x01, 0xc9, 0x73, 0xae, 0x89,
	0x66, 0x3c, 0x57, 0x65, 0xd7, 0x3f, 0x85, 0xbd, 0x03, 0xaa, 0x8f, 0xd7, 0x42, 0xa4, 0x8c, 0xca,
	0x23, 0xa6, 0x74, 0x4c, 0xaf, 0xd7, 0x54, 0x69, 0x84, 0xa0, 0x93, 0x93, 0x8c, 0xba, 0x60, 0x08,
	0x46, 0xad, 0xd8, 0xd6, 0x68, 0x0c, 0x1b, 0x82, 0x24, 0x54, 0xba, 0xb5, 0x21, 0x18, 0xb5, 0x27,
	0xdf, 0x70, 0x15, 0xd3, 0x6e, 0x57, 0x84, 0x38, 0x32, 0xcd, 0xb8, 0x64, 0xfc, 0x27, 0x00, 0xfb,
	0x3b, 0x6e, 0x25, 0x78, 0xae, 0xa8, 0x91, 0x2f, 0xf9, 0xaa, 0x94, 0x37, 0x62, 0x5b, 0xa3, 0xaf,
	0xb0, 0x9e, 0xa9, 0xc4, 0xaa, 0x5b, 0xb1, 0x29, 0xd1, 0x1e, 0x74, 0x56, 0x44, 0x13, 0xb7, 0x6e,
	0x77, 0x1b, 0xe3, 0x8d, 0x4b, 0xc1, 0x6f, 0xb8, 0xf1, 0x8c, 0x68, 0x12, 0xdb, 0x1f, 0xbd, 0x0b,
	0xe8, 0x98, 0x2f, 0x34, 0x86, 0x4e, 0xca, 0x94, 0x76, 0xc1, 0xb0, 0x3e, 0x6a, 0x4f, 0xfa, 0x5b,
	0xa2, 0x57, 0x4b, 0x6c, 0xa1, 0x4f, 0x1d, 0x72, 0x72, 0x07, 0x60, 0x73, 0x2e, 0xc5, 0x7e, 0x74,
	0x88, 0x6e, 0xe0, 0x97, 0xad, 0x48, 0xe8, 0xd7, 0x7b, 0x91, 0xed, 0x55, 0x7b, 0xbf, 0x3f, 0x76,
	0x32, 0x7f, 0x70, 0xfb, 0xf8, 0x7c, 0x5f, 0xeb, 0xf9, 0x5d, 0x3b, 0xcc, 0x22, 0x0c, 0x54, 0x45,
	0xa9, 0xff, 0xe0, 0xcf, 0xf4, 0x1f, 0xec, 0x2e, 0x79, 0xb6, 0xa9, 0x9a, 0xb6, 0x4d, 0x38, 0xc1,
	0x22, 0x33, 0xec, 0x08, 0x9c, 0x35, 0xa8, 0x14, 0x45, 0xf8, 0x50, 0xeb, 0xcc, 0x2c, 0xb5, 0x98,
	0x4b, 0xb1, 0x38, 0x09, 0x2f, 0x9b, 0xf6, 0x31, 0xfc, 0x7d, 0x09, 0x00, 0x00, 0xff, 0xff, 0xb6,
	0xe6, 0x04, 0xb0, 0x94, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ErpAPIClient is the client API for ErpAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ErpAPIClient interface {
	//GetSupplierList 获取供货商列表.
	GetSupplierList(ctx context.Context, in *GetSupplierListRequest, opts ...grpc.CallOption) (*GetSupplierListResponse, error)
}

type erpAPIClient struct {
	cc *grpc.ClientConn
}

func NewErpAPIClient(cc *grpc.ClientConn) ErpAPIClient {
	return &erpAPIClient{cc}
}

func (c *erpAPIClient) GetSupplierList(ctx context.Context, in *GetSupplierListRequest, opts ...grpc.CallOption) (*GetSupplierListResponse, error) {
	out := new(GetSupplierListResponse)
	err := c.cc.Invoke(ctx, "/donech.erp.v1.ErpAPI/GetSupplierList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ErpAPIServer is the server API for ErpAPI service.
type ErpAPIServer interface {
	//GetSupplierList 获取供货商列表.
	GetSupplierList(context.Context, *GetSupplierListRequest) (*GetSupplierListResponse, error)
}

func RegisterErpAPIServer(s *grpc.Server, srv ErpAPIServer) {
	s.RegisterService(&_ErpAPI_serviceDesc, srv)
}

func _ErpAPI_GetSupplierList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSupplierListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ErpAPIServer).GetSupplierList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/donech.erp.v1.ErpAPI/GetSupplierList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ErpAPIServer).GetSupplierList(ctx, req.(*GetSupplierListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ErpAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "donech.erp.v1.ErpAPI",
	HandlerType: (*ErpAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSupplierList",
			Handler:    _ErpAPI_GetSupplierList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "donech/erp/v1/erp_api.proto",
}
