// Code generated by protoc-gen-go. DO NOT EDIT.
// source: donech/erp/v1/erp_message.proto

package erpv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//RelationType 联系方式枚举.
type RelationType int32

const (
	RelationType_RELATION_TYPE_INVALID RelationType = 0
	RelationType_RELATION_TYPE_QQ      RelationType = 1
	RelationType_RELATION_TYPE_TEL     RelationType = 2
	RelationType_RELATION_TYPE_EMAIL   RelationType = 3
	RelationType_RELATION_TYPE_ADDRESS RelationType = 4
)

var RelationType_name = map[int32]string{
	0: "RELATION_TYPE_INVALID",
	1: "RELATION_TYPE_QQ",
	2: "RELATION_TYPE_TEL",
	3: "RELATION_TYPE_EMAIL",
	4: "RELATION_TYPE_ADDRESS",
}

var RelationType_value = map[string]int32{
	"RELATION_TYPE_INVALID": 0,
	"RELATION_TYPE_QQ":      1,
	"RELATION_TYPE_TEL":     2,
	"RELATION_TYPE_EMAIL":   3,
	"RELATION_TYPE_ADDRESS": 4,
}

func (x RelationType) String() string {
	return proto.EnumName(RelationType_name, int32(x))
}

func (RelationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_be8e619e160c9526, []int{0}
}

//Supplier 供货商.
type Supplier struct {
	Id                   int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string     `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Contacts             []*Contact `protobuf:"bytes,4,rep,name=contacts,proto3" json:"contacts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Supplier) Reset()         { *m = Supplier{} }
func (m *Supplier) String() string { return proto.CompactTextString(m) }
func (*Supplier) ProtoMessage()    {}
func (*Supplier) Descriptor() ([]byte, []int) {
	return fileDescriptor_be8e619e160c9526, []int{0}
}

func (m *Supplier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Supplier.Unmarshal(m, b)
}
func (m *Supplier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Supplier.Marshal(b, m, deterministic)
}
func (m *Supplier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Supplier.Merge(m, src)
}
func (m *Supplier) XXX_Size() int {
	return xxx_messageInfo_Supplier.Size(m)
}
func (m *Supplier) XXX_DiscardUnknown() {
	xxx_messageInfo_Supplier.DiscardUnknown(m)
}

var xxx_messageInfo_Supplier proto.InternalMessageInfo

func (m *Supplier) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Supplier) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Supplier) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Supplier) GetContacts() []*Contact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

//Contact 供货商联系人.
type Contact struct {
	Id                   int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SupplierId           int64       `protobuf:"varint,2,opt,name=supplier_id,json=supplierId,proto3" json:"supplier_id,omitempty"`
	Title                string      `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Firstname            string      `protobuf:"bytes,4,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string      `protobuf:"bytes,5,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Relations            []*Relation `protobuf:"bytes,6,rep,name=relations,proto3" json:"relations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}
func (*Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_be8e619e160c9526, []int{1}
}

func (m *Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact.Unmarshal(m, b)
}
func (m *Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact.Marshal(b, m, deterministic)
}
func (m *Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact.Merge(m, src)
}
func (m *Contact) XXX_Size() int {
	return xxx_messageInfo_Contact.Size(m)
}
func (m *Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Contact proto.InternalMessageInfo

func (m *Contact) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Contact) GetSupplierId() int64 {
	if m != nil {
		return m.SupplierId
	}
	return 0
}

func (m *Contact) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Contact) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *Contact) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *Contact) GetRelations() []*Relation {
	if m != nil {
		return m.Relations
	}
	return nil
}

//Relation 供货商联系方式.
type Relation struct {
	Id                   int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ContactId            int64        `protobuf:"varint,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	Type                 RelationType `protobuf:"varint,3,opt,name=type,proto3,enum=donech.erp.v1.RelationType" json:"type,omitempty"`
	Value                string       `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Relation) Reset()         { *m = Relation{} }
func (m *Relation) String() string { return proto.CompactTextString(m) }
func (*Relation) ProtoMessage()    {}
func (*Relation) Descriptor() ([]byte, []int) {
	return fileDescriptor_be8e619e160c9526, []int{2}
}

func (m *Relation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Relation.Unmarshal(m, b)
}
func (m *Relation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Relation.Marshal(b, m, deterministic)
}
func (m *Relation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Relation.Merge(m, src)
}
func (m *Relation) XXX_Size() int {
	return xxx_messageInfo_Relation.Size(m)
}
func (m *Relation) XXX_DiscardUnknown() {
	xxx_messageInfo_Relation.DiscardUnknown(m)
}

var xxx_messageInfo_Relation proto.InternalMessageInfo

func (m *Relation) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Relation) GetContactId() int64 {
	if m != nil {
		return m.ContactId
	}
	return 0
}

func (m *Relation) GetType() RelationType {
	if m != nil {
		return m.Type
	}
	return RelationType_RELATION_TYPE_INVALID
}

func (m *Relation) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterEnum("donech.erp.v1.RelationType", RelationType_name, RelationType_value)
	proto.RegisterType((*Supplier)(nil), "donech.erp.v1.Supplier")
	proto.RegisterType((*Contact)(nil), "donech.erp.v1.Contact")
	proto.RegisterType((*Relation)(nil), "donech.erp.v1.Relation")
}

func init() { proto.RegisterFile("donech/erp/v1/erp_message.proto", fileDescriptor_be8e619e160c9526) }

var fileDescriptor_be8e619e160c9526 = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4f, 0x6b, 0xdb, 0x30,
	0x18, 0xc6, 0x27, 0xdb, 0x69, 0x93, 0xb7, 0x6b, 0xe7, 0x6a, 0xed, 0xea, 0xfd, 0xa3, 0x21, 0xa7,
	0xb0, 0x83, 0x43, 0x32, 0x76, 0xdc, 0x21, 0x9d, 0x7d, 0x30, 0xb8, 0x5d, 0xaa, 0x98, 0xc2, 0x46,
	0xc1, 0x78, 0x96, 0xb6, 0x19, 0x1c, 0x5b, 0x48, 0xaa, 0xa1, 0xb0, 0xc3, 0xce, 0xfb, 0x56, 0xbb,
	0xee, 0x53, 0x8d, 0xc8, 0x76, 0x32, 0x2f, 0xf4, 0x24, 0xbd, 0xcf, 0xf3, 0xc0, 0xfb, 0xfc, 0xe0,
	0x85, 0x73, 0x5a, 0x16, 0x2c, 0xfd, 0x3e, 0x61, 0x82, 0x4f, 0xaa, 0xe9, 0xfa, 0x89, 0x57, 0x4c,
	0xca, 0xe4, 0x1b, 0x73, 0xb9, 0x28, 0x55, 0x89, 0x0f, 0xeb, 0x80, 0xcb, 0x04, 0x77, 0xab, 0xe9,
	0xe8, 0x07, 0xf4, 0x97, 0x77, 0x9c, 0xe7, 0x19, 0x13, 0xf8, 0x08, 0x8c, 0x8c, 0x3a, 0x68, 0x88,
	0xc6, 0x26, 0x31, 0x32, 0x8a, 0x31, 0x58, 0x45, 0xb2, 0x62, 0x8e, 0x31, 0x44, 0xe3, 0x01, 0xd1,
	0x7f, 0xec, 0xc0, 0x7e, 0x42, 0xa9, 0x60, 0x52, 0x3a, 0xa6, 0x96, 0xdb, 0x11, 0xcf, 0xa0, 0x9f,
	0x96, 0x85, 0x4a, 0x52, 0x25, 0x1d, 0x6b, 0x68, 0x8e, 0x0f, 0x66, 0xcf, 0xdc, 0xce, 0x2e, 0xf7,
	0x43, 0x6d, 0x93, 0x4d, 0x6e, 0xf4, 0x1b, 0xc1, 0x7e, 0xa3, 0xee, 0x6c, 0x3f, 0x87, 0x03, 0xd9,
	0x34, 0x8b, 0x33, 0xaa, 0x4b, 0x98, 0x04, 0x5a, 0x29, 0xa0, 0xf8, 0x04, 0x7a, 0x2a, 0x53, 0x39,
	0x6b, 0x8a, 0xd4, 0x03, 0x7e, 0x05, 0x83, 0xaf, 0x99, 0x90, 0x4a, 0x37, 0xb7, 0xb4, 0xb3, 0x15,
	0xf0, 0x0b, 0xe8, 0xe7, 0x49, 0x63, 0xf6, 0xb4, 0xb9, 0x99, 0xf1, 0x3b, 0x18, 0x08, 0x96, 0x27,
	0x2a, 0x2b, 0x0b, 0xe9, 0xec, 0x69, 0x82, 0xb3, 0xff, 0x08, 0x48, 0xe3, 0x93, 0x6d, 0x72, 0xf4,
	0x13, 0x41, 0xbf, 0xd5, 0x77, 0x20, 0x5e, 0x03, 0x34, 0xb0, 0x5b, 0x86, 0x41, 0xa3, 0x04, 0x14,
	0x4f, 0xc0, 0x52, 0xf7, 0xbc, 0x26, 0x38, 0x9a, 0xbd, 0x7c, 0x60, 0x5b, 0x74, 0xcf, 0x19, 0xd1,
	0xc1, 0x35, 0x73, 0x95, 0xe4, 0x77, 0x2d, 0x59, 0x3d, 0xbc, 0xf9, 0x85, 0xe0, 0xf1, 0xbf, 0x61,
	0xfc, 0x1c, 0x4e, 0x89, 0x1f, 0xce, 0xa3, 0xe0, 0xe3, 0x55, 0x1c, 0x7d, 0x5a, 0xf8, 0x71, 0x70,
	0x75, 0x33, 0x0f, 0x03, 0xcf, 0x7e, 0x84, 0x4f, 0xc0, 0xee, 0x5a, 0xd7, 0xd7, 0x36, 0xc2, 0xa7,
	0x70, 0xdc, 0x55, 0x23, 0x3f, 0xb4, 0x0d, 0x7c, 0x06, 0x4f, 0xbb, 0xb2, 0x7f, 0x39, 0x0f, 0x42,
	0xdb, 0xdc, 0x5d, 0x30, 0xf7, 0x3c, 0xe2, 0x2f, 0x97, 0xb6, 0x75, 0xf1, 0x1e, 0x8e, 0xd3, 0x72,
	0xd5, 0x45, 0xb9, 0x78, 0xe2, 0x0b, 0x7e, 0x59, 0xdf, 0xe1, 0x62, 0x7d, 0x86, 0x0b, 0xf4, 0xb9,
	0xc7, 0x04, 0xaf, 0xa6, 0x7f, 0x8c, 0x43, 0x4f, 0x27, 0x6f, 0x7d, 0xc1, 0x6f, 0x6f, 0xa6, 0x5f,
	0xf6, 0xf4, 0x99, 0xbe, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x7d, 0xc7, 0x39, 0xbb, 0xc9, 0x02,
	0x00, 0x00,
}
