// Code generated by protoc-gen-go. DO NOT EDIT.
// source: donech/erp/v1/messages.proto

package erpv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//RelationType 联系方式枚举.
type RelationType int32

const (
	RelationType_RELATION_TYPE_INVALID RelationType = 0
	RelationType_RELATION_TYPE_QQ      RelationType = 1
	RelationType_RELATION_TYPE_TEL     RelationType = 2
	RelationType_RELATION_TYPE_EMAIL   RelationType = 3
	RelationType_RELATION_TYPE_ADDRESS RelationType = 4
)

var RelationType_name = map[int32]string{
	0: "RELATION_TYPE_INVALID",
	1: "RELATION_TYPE_QQ",
	2: "RELATION_TYPE_TEL",
	3: "RELATION_TYPE_EMAIL",
	4: "RELATION_TYPE_ADDRESS",
}

var RelationType_value = map[string]int32{
	"RELATION_TYPE_INVALID": 0,
	"RELATION_TYPE_QQ":      1,
	"RELATION_TYPE_TEL":     2,
	"RELATION_TYPE_EMAIL":   3,
	"RELATION_TYPE_ADDRESS": 4,
}

func (x RelationType) String() string {
	return proto.EnumName(RelationType_name, int32(x))
}

func (RelationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b368b02404b0de6c, []int{0}
}

//Pager 通用分页信息.
type Pager struct {
	PageSize             int32    `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageNum              int32    `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	Cursor               int64    `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	HasMore              bool     `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	Total                int32    `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pager) Reset()         { *m = Pager{} }
func (m *Pager) String() string { return proto.CompactTextString(m) }
func (*Pager) ProtoMessage()    {}
func (*Pager) Descriptor() ([]byte, []int) {
	return fileDescriptor_b368b02404b0de6c, []int{0}
}

func (m *Pager) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pager.Unmarshal(m, b)
}
func (m *Pager) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pager.Marshal(b, m, deterministic)
}
func (m *Pager) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pager.Merge(m, src)
}
func (m *Pager) XXX_Size() int {
	return xxx_messageInfo_Pager.Size(m)
}
func (m *Pager) XXX_DiscardUnknown() {
	xxx_messageInfo_Pager.DiscardUnknown(m)
}

var xxx_messageInfo_Pager proto.InternalMessageInfo

func (m *Pager) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *Pager) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *Pager) GetCursor() int64 {
	if m != nil {
		return m.Cursor
	}
	return 0
}

func (m *Pager) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

func (m *Pager) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

//CursorPager 游标分页信息.
type CursorPager struct {
	PageSize             int32    `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Cursor               int64    `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	HasMore              bool     `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CursorPager) Reset()         { *m = CursorPager{} }
func (m *CursorPager) String() string { return proto.CompactTextString(m) }
func (*CursorPager) ProtoMessage()    {}
func (*CursorPager) Descriptor() ([]byte, []int) {
	return fileDescriptor_b368b02404b0de6c, []int{1}
}

func (m *CursorPager) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CursorPager.Unmarshal(m, b)
}
func (m *CursorPager) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CursorPager.Marshal(b, m, deterministic)
}
func (m *CursorPager) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CursorPager.Merge(m, src)
}
func (m *CursorPager) XXX_Size() int {
	return xxx_messageInfo_CursorPager.Size(m)
}
func (m *CursorPager) XXX_DiscardUnknown() {
	xxx_messageInfo_CursorPager.DiscardUnknown(m)
}

var xxx_messageInfo_CursorPager proto.InternalMessageInfo

func (m *CursorPager) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *CursorPager) GetCursor() int64 {
	if m != nil {
		return m.Cursor
	}
	return 0
}

func (m *CursorPager) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

//Supplier 供货商.
type Supplier struct {
	Id                   int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string     `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Contacts             []*Contact `protobuf:"bytes,4,rep,name=contacts,proto3" json:"contacts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Supplier) Reset()         { *m = Supplier{} }
func (m *Supplier) String() string { return proto.CompactTextString(m) }
func (*Supplier) ProtoMessage()    {}
func (*Supplier) Descriptor() ([]byte, []int) {
	return fileDescriptor_b368b02404b0de6c, []int{2}
}

func (m *Supplier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Supplier.Unmarshal(m, b)
}
func (m *Supplier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Supplier.Marshal(b, m, deterministic)
}
func (m *Supplier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Supplier.Merge(m, src)
}
func (m *Supplier) XXX_Size() int {
	return xxx_messageInfo_Supplier.Size(m)
}
func (m *Supplier) XXX_DiscardUnknown() {
	xxx_messageInfo_Supplier.DiscardUnknown(m)
}

var xxx_messageInfo_Supplier proto.InternalMessageInfo

func (m *Supplier) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Supplier) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Supplier) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Supplier) GetContacts() []*Contact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

//Contact 供货商联系人.
type Contact struct {
	Id                   int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SupplierId           int64       `protobuf:"varint,2,opt,name=supplier_id,json=supplierId,proto3" json:"supplier_id,omitempty"`
	Title                string      `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Firstname            string      `protobuf:"bytes,4,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string      `protobuf:"bytes,5,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Relations            []*Relation `protobuf:"bytes,6,rep,name=relations,proto3" json:"relations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}
func (*Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_b368b02404b0de6c, []int{3}
}

func (m *Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact.Unmarshal(m, b)
}
func (m *Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact.Marshal(b, m, deterministic)
}
func (m *Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact.Merge(m, src)
}
func (m *Contact) XXX_Size() int {
	return xxx_messageInfo_Contact.Size(m)
}
func (m *Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Contact proto.InternalMessageInfo

func (m *Contact) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Contact) GetSupplierId() int64 {
	if m != nil {
		return m.SupplierId
	}
	return 0
}

func (m *Contact) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Contact) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *Contact) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *Contact) GetRelations() []*Relation {
	if m != nil {
		return m.Relations
	}
	return nil
}

//Relation 供货商联系方式.
type Relation struct {
	Id                   int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ContactId            int64        `protobuf:"varint,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	Type                 RelationType `protobuf:"varint,3,opt,name=type,proto3,enum=donech.erp.v1.RelationType" json:"type,omitempty"`
	Value                string       `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Relation) Reset()         { *m = Relation{} }
func (m *Relation) String() string { return proto.CompactTextString(m) }
func (*Relation) ProtoMessage()    {}
func (*Relation) Descriptor() ([]byte, []int) {
	return fileDescriptor_b368b02404b0de6c, []int{4}
}

func (m *Relation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Relation.Unmarshal(m, b)
}
func (m *Relation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Relation.Marshal(b, m, deterministic)
}
func (m *Relation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Relation.Merge(m, src)
}
func (m *Relation) XXX_Size() int {
	return xxx_messageInfo_Relation.Size(m)
}
func (m *Relation) XXX_DiscardUnknown() {
	xxx_messageInfo_Relation.DiscardUnknown(m)
}

var xxx_messageInfo_Relation proto.InternalMessageInfo

func (m *Relation) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Relation) GetContactId() int64 {
	if m != nil {
		return m.ContactId
	}
	return 0
}

func (m *Relation) GetType() RelationType {
	if m != nil {
		return m.Type
	}
	return RelationType_RELATION_TYPE_INVALID
}

func (m *Relation) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterEnum("donech.erp.v1.RelationType", RelationType_name, RelationType_value)
	proto.RegisterType((*Pager)(nil), "donech.erp.v1.Pager")
	proto.RegisterType((*CursorPager)(nil), "donech.erp.v1.CursorPager")
	proto.RegisterType((*Supplier)(nil), "donech.erp.v1.Supplier")
	proto.RegisterType((*Contact)(nil), "donech.erp.v1.Contact")
	proto.RegisterType((*Relation)(nil), "donech.erp.v1.Relation")
}

func init() { proto.RegisterFile("donech/erp/v1/messages.proto", fileDescriptor_b368b02404b0de6c) }

var fileDescriptor_b368b02404b0de6c = []byte{
	// 513 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x6f, 0xda, 0x30,
	0x18, 0x5e, 0xbe, 0x4a, 0xf2, 0x32, 0xaa, 0xd4, 0xeb, 0x47, 0xba, 0x76, 0x1a, 0xe2, 0x84, 0x76,
	0x00, 0xc1, 0xb4, 0xd3, 0x4e, 0xb4, 0xe4, 0x10, 0x09, 0x18, 0x35, 0xa8, 0xd2, 0xa6, 0x4e, 0x91,
	0x47, 0x3c, 0x88, 0x94, 0x10, 0xcb, 0x0e, 0x48, 0xad, 0x76, 0xd8, 0x71, 0xda, 0xbf, 0xda, 0x75,
	0xbf, 0x6a, 0xc2, 0x31, 0x65, 0x19, 0xaa, 0xb4, 0x9b, 0x9f, 0x0f, 0xbf, 0xcf, 0xfb, 0x58, 0x32,
	0x5c, 0x46, 0xd9, 0x92, 0xce, 0x16, 0x6d, 0xca, 0x59, 0x7b, 0xdd, 0x69, 0xa7, 0x54, 0x08, 0x32,
	0xa7, 0xa2, 0xc5, 0x78, 0x96, 0x67, 0xa8, 0x56, 0xa8, 0x2d, 0xca, 0x59, 0x6b, 0xdd, 0x69, 0xfc,
	0xd0, 0xc0, 0x1a, 0x93, 0x39, 0xe5, 0xe8, 0x02, 0x1c, 0x46, 0xe6, 0x34, 0x14, 0xf1, 0x03, 0xf5,
	0xb4, 0xba, 0xd6, 0xb4, 0xb0, 0xbd, 0x21, 0x26, 0xf1, 0x03, 0x45, 0xe7, 0x20, 0xcf, 0xe1, 0x72,
	0x95, 0x7a, 0xba, 0xd4, 0x2a, 0x1b, 0x3c, 0x5a, 0xa5, 0xe8, 0x14, 0x0e, 0x66, 0x2b, 0x2e, 0x32,
	0xee, 0x19, 0x75, 0xad, 0x69, 0x60, 0x85, 0x36, 0x57, 0x16, 0x44, 0x84, 0x69, 0xc6, 0xa9, 0x67,
	0xd6, 0xb5, 0xa6, 0x8d, 0x2b, 0x0b, 0x22, 0x86, 0x19, 0xa7, 0xe8, 0x18, 0xac, 0x3c, 0xcb, 0x49,
	0xe2, 0x59, 0x72, 0x54, 0x01, 0x1a, 0x9f, 0xa1, 0x7a, 0x2d, 0xaf, 0xfe, 0xc7, 0x3e, 0xbb, 0x50,
	0xfd, 0xc9, 0x50, 0xa3, 0x14, 0xda, 0xf8, 0x06, 0xf6, 0x64, 0xc5, 0x58, 0x12, 0x53, 0x8e, 0x0e,
	0x41, 0x8f, 0x23, 0x39, 0xd4, 0xc0, 0x7a, 0x1c, 0x21, 0x04, 0xe6, 0x92, 0xa4, 0x54, 0x0e, 0x73,
	0xb0, 0x3c, 0x23, 0x0f, 0x2a, 0x24, 0x8a, 0x38, 0x15, 0x42, 0x4e, 0x72, 0xf0, 0x16, 0xa2, 0x2e,
	0xd8, 0xb3, 0x6c, 0x99, 0x93, 0x59, 0x2e, 0x3c, 0xb3, 0x6e, 0x34, 0xab, 0xdd, 0xd3, 0x56, 0xe9,
	0x55, 0x5b, 0xd7, 0x85, 0x8c, 0x1f, 0x7d, 0x8d, 0x5f, 0x1a, 0x54, 0x14, 0xbb, 0x97, 0xfe, 0x1a,
	0xaa, 0x42, 0x6d, 0x16, 0xc6, 0x91, 0x6a, 0x04, 0x5b, 0x2a, 0x88, 0xe4, 0x7b, 0xc5, 0x79, 0x42,
	0xd5, 0x22, 0x05, 0x40, 0x97, 0xe0, 0x7c, 0x8d, 0xb9, 0xc8, 0xe5, 0xe6, 0xa6, 0x54, 0x76, 0x04,
	0x7a, 0x09, 0x76, 0x42, 0x94, 0x68, 0x49, 0xf1, 0x11, 0xa3, 0x77, 0xe0, 0x70, 0x9a, 0x90, 0x3c,
	0xce, 0x96, 0xc2, 0x3b, 0x90, 0x0d, 0xce, 0xfe, 0x69, 0x80, 0x95, 0x8e, 0x77, 0xce, 0xc6, 0x77,
	0x0d, 0xec, 0x2d, 0xbf, 0x57, 0xe2, 0x15, 0x80, 0x2a, 0xbb, 0xeb, 0xe0, 0x28, 0x26, 0x88, 0x50,
	0x1b, 0xcc, 0xfc, 0x9e, 0x15, 0x0d, 0x0e, 0xbb, 0x17, 0x4f, 0xa4, 0x4d, 0xef, 0x19, 0xc5, 0xd2,
	0xb8, 0xe9, 0xbc, 0x26, 0xc9, 0x6a, 0xdb, 0xac, 0x00, 0x6f, 0x7e, 0x6a, 0xf0, 0xfc, 0x6f, 0x33,
	0x3a, 0x87, 0x13, 0xec, 0x0f, 0x7a, 0xd3, 0xe0, 0xc3, 0x28, 0x9c, 0x7e, 0x1c, 0xfb, 0x61, 0x30,
	0xba, 0xed, 0x0d, 0x82, 0xbe, 0xfb, 0x0c, 0x1d, 0x83, 0x5b, 0x96, 0x6e, 0x6e, 0x5c, 0x0d, 0x9d,
	0xc0, 0x51, 0x99, 0x9d, 0xfa, 0x03, 0x57, 0x47, 0x67, 0xf0, 0xa2, 0x4c, 0xfb, 0xc3, 0x5e, 0x30,
	0x70, 0x8d, 0xfd, 0x80, 0x5e, 0xbf, 0x8f, 0xfd, 0xc9, 0xc4, 0x35, 0xaf, 0xde, 0xc3, 0xd1, 0x2c,
	0x4b, 0xcb, 0x55, 0xae, 0x6a, 0x43, 0xf5, 0xdf, 0xc6, 0x9b, 0xef, 0x36, 0xd6, 0x3e, 0x59, 0x94,
	0xb3, 0x75, 0xe7, 0xb7, 0x5e, 0xeb, 0x4b, 0xdf, 0x9d, 0xcf, 0xd9, 0xdd, 0x6d, 0xe7, 0xcb, 0x81,
	0xfc, 0x8e, 0x6f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x1b, 0x54, 0xc0, 0xae, 0x03, 0x00,
	0x00,
}
