// Code generated by protoc-gen-go. DO NOT EDIT.
// source: donech/erp/v1/system_api.proto

package erpv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//SaveUserRequest.
type SaveUserRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveUserRequest) Reset()         { *m = SaveUserRequest{} }
func (m *SaveUserRequest) String() string { return proto.CompactTextString(m) }
func (*SaveUserRequest) ProtoMessage()    {}
func (*SaveUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f156e956f157d9a, []int{0}
}

func (m *SaveUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveUserRequest.Unmarshal(m, b)
}
func (m *SaveUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveUserRequest.Marshal(b, m, deterministic)
}
func (m *SaveUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveUserRequest.Merge(m, src)
}
func (m *SaveUserRequest) XXX_Size() int {
	return xxx_messageInfo_SaveUserRequest.Size(m)
}
func (m *SaveUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveUserRequest proto.InternalMessageInfo

func (m *SaveUserRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *SaveUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SaveUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

//SaveUserResponse.
type SaveUserResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveUserResponse) Reset()         { *m = SaveUserResponse{} }
func (m *SaveUserResponse) String() string { return proto.CompactTextString(m) }
func (*SaveUserResponse) ProtoMessage()    {}
func (*SaveUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f156e956f157d9a, []int{1}
}

func (m *SaveUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveUserResponse.Unmarshal(m, b)
}
func (m *SaveUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveUserResponse.Marshal(b, m, deterministic)
}
func (m *SaveUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveUserResponse.Merge(m, src)
}
func (m *SaveUserResponse) XXX_Size() int {
	return xxx_messageInfo_SaveUserResponse.Size(m)
}
func (m *SaveUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveUserResponse proto.InternalMessageInfo

func (m *SaveUserResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SaveUserResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

//UsersRequest.
type UsersRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pager                *Pager   `protobuf:"bytes,2,opt,name=pager,proto3" json:"pager,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersRequest) Reset()         { *m = UsersRequest{} }
func (m *UsersRequest) String() string { return proto.CompactTextString(m) }
func (*UsersRequest) ProtoMessage()    {}
func (*UsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f156e956f157d9a, []int{2}
}

func (m *UsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersRequest.Unmarshal(m, b)
}
func (m *UsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersRequest.Marshal(b, m, deterministic)
}
func (m *UsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersRequest.Merge(m, src)
}
func (m *UsersRequest) XXX_Size() int {
	return xxx_messageInfo_UsersRequest.Size(m)
}
func (m *UsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsersRequest proto.InternalMessageInfo

func (m *UsersRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UsersRequest) GetPager() *Pager {
	if m != nil {
		return m.Pager
	}
	return nil
}

//UsersResponse.
type UsersResponse struct {
	Code                 int32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string                `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 []*UsersResponse_Data `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pager                *Pager                `protobuf:"bytes,4,opt,name=pager,proto3" json:"pager,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UsersResponse) Reset()         { *m = UsersResponse{} }
func (m *UsersResponse) String() string { return proto.CompactTextString(m) }
func (*UsersResponse) ProtoMessage()    {}
func (*UsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f156e956f157d9a, []int{3}
}

func (m *UsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersResponse.Unmarshal(m, b)
}
func (m *UsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersResponse.Marshal(b, m, deterministic)
}
func (m *UsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersResponse.Merge(m, src)
}
func (m *UsersResponse) XXX_Size() int {
	return xxx_messageInfo_UsersResponse.Size(m)
}
func (m *UsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsersResponse proto.InternalMessageInfo

func (m *UsersResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UsersResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *UsersResponse) GetData() []*UsersResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UsersResponse) GetPager() *Pager {
	if m != nil {
		return m.Pager
	}
	return nil
}

//Data.
type UsersResponse_Data struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Account              string   `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	CreatedTime          string   `protobuf:"bytes,4,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersResponse_Data) Reset()         { *m = UsersResponse_Data{} }
func (m *UsersResponse_Data) String() string { return proto.CompactTextString(m) }
func (*UsersResponse_Data) ProtoMessage()    {}
func (*UsersResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f156e956f157d9a, []int{3, 0}
}

func (m *UsersResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersResponse_Data.Unmarshal(m, b)
}
func (m *UsersResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersResponse_Data.Marshal(b, m, deterministic)
}
func (m *UsersResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersResponse_Data.Merge(m, src)
}
func (m *UsersResponse_Data) XXX_Size() int {
	return xxx_messageInfo_UsersResponse_Data.Size(m)
}
func (m *UsersResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_UsersResponse_Data proto.InternalMessageInfo

func (m *UsersResponse_Data) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UsersResponse_Data) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UsersResponse_Data) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UsersResponse_Data) GetCreatedTime() string {
	if m != nil {
		return m.CreatedTime
	}
	return ""
}

//CheckAccountRequest.
type CheckAccountRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckAccountRequest) Reset()         { *m = CheckAccountRequest{} }
func (m *CheckAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CheckAccountRequest) ProtoMessage()    {}
func (*CheckAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f156e956f157d9a, []int{4}
}

func (m *CheckAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckAccountRequest.Unmarshal(m, b)
}
func (m *CheckAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckAccountRequest.Marshal(b, m, deterministic)
}
func (m *CheckAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckAccountRequest.Merge(m, src)
}
func (m *CheckAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CheckAccountRequest.Size(m)
}
func (m *CheckAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckAccountRequest proto.InternalMessageInfo

func (m *CheckAccountRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

//CheckAccountResponse.
type CheckAccountResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckAccountResponse) Reset()         { *m = CheckAccountResponse{} }
func (m *CheckAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CheckAccountResponse) ProtoMessage()    {}
func (*CheckAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f156e956f157d9a, []int{5}
}

func (m *CheckAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckAccountResponse.Unmarshal(m, b)
}
func (m *CheckAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckAccountResponse.Marshal(b, m, deterministic)
}
func (m *CheckAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckAccountResponse.Merge(m, src)
}
func (m *CheckAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CheckAccountResponse.Size(m)
}
func (m *CheckAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckAccountResponse proto.InternalMessageInfo

func (m *CheckAccountResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CheckAccountResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*SaveUserRequest)(nil), "donech.erp.v1.SaveUserRequest")
	proto.RegisterType((*SaveUserResponse)(nil), "donech.erp.v1.SaveUserResponse")
	proto.RegisterType((*UsersRequest)(nil), "donech.erp.v1.UsersRequest")
	proto.RegisterType((*UsersResponse)(nil), "donech.erp.v1.UsersResponse")
	proto.RegisterType((*UsersResponse_Data)(nil), "donech.erp.v1.UsersResponse.Data")
	proto.RegisterType((*CheckAccountRequest)(nil), "donech.erp.v1.CheckAccountRequest")
	proto.RegisterType((*CheckAccountResponse)(nil), "donech.erp.v1.CheckAccountResponse")
}

func init() { proto.RegisterFile("donech/erp/v1/system_api.proto", fileDescriptor_0f156e956f157d9a) }

var fileDescriptor_0f156e956f157d9a = []byte{
	// 502 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0xed, 0x04, 0xda, 0x49, 0xd2, 0x96, 0xa5, 0x95, 0x2c, 0x13, 0x95, 0x74, 0xb9, 0x54,
	0x3d, 0xd8, 0x72, 0x10, 0x12, 0x42, 0xbd, 0xb4, 0x94, 0x03, 0x17, 0x14, 0xb9, 0x80, 0x04, 0x54,
	0xaa, 0x16, 0x7b, 0xe4, 0x5a, 0x60, 0xef, 0xe2, 0xdd, 0x18, 0xf5, 0x08, 0xbf, 0xc0, 0x4f, 0x21,
	0xae, 0xfc, 0x02, 0x1f, 0x82, 0x76, 0x6d, 0xd3, 0x38, 0x0a, 0xad, 0x7a, 0x5b, 0xef, 0xcc, 0xbc,
	0xf7, 0xfc, 0xe6, 0x2d, 0xec, 0x26, 0xbc, 0xc0, 0xf8, 0x22, 0xc0, 0x52, 0x04, 0x55, 0x18, 0xc8,
	0x4b, 0xa9, 0x30, 0x3f, 0x67, 0x22, 0xf3, 0x45, 0xc9, 0x15, 0x27, 0xa3, 0xba, 0xee, 0x63, 0x29,
	0xfc, 0x2a, 0xf4, 0xc6, 0xdd, 0xf6, 0x1c, 0xa5, 0x64, 0x29, 0xca, 0xba, 0xd9, 0x1b, 0xa7, 0x9c,
	0xa7, 0x9f, 0x31, 0x60, 0x22, 0x0b, 0x58, 0x51, 0x70, 0xc5, 0x54, 0xc6, 0x8b, 0xa6, 0x4a, 0x3f,
	0xc0, 0xe6, 0x29, 0xab, 0xf0, 0x8d, 0xc4, 0x32, 0xc2, 0x2f, 0x73, 0x94, 0x8a, 0xb8, 0x70, 0x97,
	0xc5, 0x31, 0x9f, 0x17, 0xca, 0xb5, 0x26, 0xd6, 0xfe, 0x7a, 0xd4, 0x7e, 0x12, 0x02, 0xbd, 0x82,
	0xe5, 0xe8, 0xda, 0xe6, 0xda, 0x9c, 0x89, 0x07, 0x6b, 0x82, 0x49, 0xf9, 0x95, 0x97, 0x89, 0xeb,
	0x98, 0xfb, 0x7f, 0xdf, 0xf4, 0x29, 0x6c, 0x5d, 0x81, 0x4b, 0xc1, 0x0b, 0x89, 0x1a, 0x23, 0xe6,
	0x09, 0x1a, 0xe8, 0x7e, 0x64, 0xce, 0x64, 0x0b, 0x9c, 0x5c, 0xa6, 0x0d, 0xac, 0x3e, 0xd2, 0x57,
	0x30, 0xd4, 0x53, 0xb2, 0xd5, 0xd4, 0x32, 0x5b, 0x0b, 0xcc, 0x07, 0xd0, 0x17, 0x2c, 0xc5, 0xd2,
	0xcc, 0x0d, 0xa6, 0xdb, 0x7e, 0xc7, 0x15, 0x7f, 0xa6, 0x6b, 0x51, 0xdd, 0x42, 0xbf, 0xd9, 0x30,
	0x6a, 0x00, 0x6f, 0xa3, 0x83, 0x3c, 0x81, 0x5e, 0xc2, 0x14, 0x73, 0x9d, 0x89, 0xb3, 0x3f, 0x98,
	0xee, 0x2d, 0x51, 0x74, 0x10, 0xfd, 0x13, 0xa6, 0x58, 0x64, 0xda, 0xaf, 0xa4, 0xf5, 0x6e, 0x94,
	0xe6, 0xa5, 0xd0, 0xd3, 0x93, 0x64, 0x03, 0xec, 0x2c, 0x31, 0x72, 0x9c, 0xc8, 0xce, 0x92, 0x95,
	0x66, 0x2f, 0xac, 0xc6, 0xe9, 0xae, 0x66, 0x0f, 0x86, 0x71, 0x89, 0x4c, 0x61, 0x72, 0xae, 0xb2,
	0x1c, 0x0d, 0xf1, 0x7a, 0x34, 0x68, 0xee, 0x5e, 0x67, 0x39, 0xd2, 0x00, 0xee, 0x3f, 0xbf, 0xc0,
	0xf8, 0xd3, 0x51, 0x3d, 0x72, 0xe3, 0xba, 0xe9, 0x21, 0x6c, 0x77, 0x07, 0x6e, 0x63, 0xdd, 0xf4,
	0xa7, 0x0d, 0xeb, 0xa7, 0x26, 0xb9, 0x47, 0xb3, 0x97, 0x04, 0x61, 0xad, 0x8d, 0x02, 0xd9, 0x5d,
	0xb2, 0x63, 0x29, 0x80, 0xde, 0xc3, 0xff, 0xd6, 0x6b, 0x01, 0xd4, 0xfd, 0xfe, 0xfb, 0xcf, 0x0f,
	0x9b, 0xd0, 0x91, 0x09, 0x75, 0x15, 0x06, 0x73, 0xbd, 0x88, 0x67, 0xd6, 0x01, 0xb9, 0x84, 0xe1,
	0xa2, 0x64, 0x42, 0x97, 0xa0, 0x56, 0x18, 0xe0, 0x3d, 0xba, 0xb6, 0xa7, 0xa1, 0x9c, 0x18, 0x4a,
	0x8f, 0xee, 0xb4, 0x94, 0xb1, 0xee, 0x0a, 0x1a, 0xab, 0x34, 0xf5, 0x3b, 0xe8, 0x9b, 0x3c, 0x90,
	0x07, 0xab, 0x53, 0x52, 0x93, 0x8d, 0xaf, 0x8b, 0x10, 0xdd, 0x31, 0x2c, 0x9b, 0xa4, 0xfb, 0x63,
	0xc7, 0x87, 0x70, 0x2f, 0xe6, 0x79, 0x77, 0xf2, 0x78, 0xa3, 0x31, 0x57, 0x64, 0x33, 0xfd, 0x92,
	0x67, 0xd6, 0xfb, 0x3e, 0x96, 0xa2, 0x0a, 0x7f, 0xd9, 0xa3, 0x13, 0xd3, 0x78, 0xf6, 0xa2, 0x14,
	0x67, 0x6f, 0xc3, 0x8f, 0x77, 0xcc, 0x4b, 0x7f, 0xfc, 0x37, 0x00, 0x00, 0xff, 0xff, 0xb9, 0x57,
	0x31, 0xa4, 0x56, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SystemAPIClient is the client API for SystemAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SystemAPIClient interface {
	//SaveUser.
	SaveUser(ctx context.Context, in *SaveUserRequest, opts ...grpc.CallOption) (*SaveUserResponse, error)
	//CheckAccount.
	CheckAccount(ctx context.Context, in *CheckAccountRequest, opts ...grpc.CallOption) (*CheckAccountResponse, error)
	//Users.
	Users(ctx context.Context, in *UsersRequest, opts ...grpc.CallOption) (*UsersResponse, error)
}

type systemAPIClient struct {
	cc *grpc.ClientConn
}

func NewSystemAPIClient(cc *grpc.ClientConn) SystemAPIClient {
	return &systemAPIClient{cc}
}

func (c *systemAPIClient) SaveUser(ctx context.Context, in *SaveUserRequest, opts ...grpc.CallOption) (*SaveUserResponse, error) {
	out := new(SaveUserResponse)
	err := c.cc.Invoke(ctx, "/donech.erp.v1.SystemAPI/SaveUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemAPIClient) CheckAccount(ctx context.Context, in *CheckAccountRequest, opts ...grpc.CallOption) (*CheckAccountResponse, error) {
	out := new(CheckAccountResponse)
	err := c.cc.Invoke(ctx, "/donech.erp.v1.SystemAPI/CheckAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemAPIClient) Users(ctx context.Context, in *UsersRequest, opts ...grpc.CallOption) (*UsersResponse, error) {
	out := new(UsersResponse)
	err := c.cc.Invoke(ctx, "/donech.erp.v1.SystemAPI/Users", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemAPIServer is the server API for SystemAPI service.
type SystemAPIServer interface {
	//SaveUser.
	SaveUser(context.Context, *SaveUserRequest) (*SaveUserResponse, error)
	//CheckAccount.
	CheckAccount(context.Context, *CheckAccountRequest) (*CheckAccountResponse, error)
	//Users.
	Users(context.Context, *UsersRequest) (*UsersResponse, error)
}

func RegisterSystemAPIServer(s *grpc.Server, srv SystemAPIServer) {
	s.RegisterService(&_SystemAPI_serviceDesc, srv)
}

func _SystemAPI_SaveUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemAPIServer).SaveUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/donech.erp.v1.SystemAPI/SaveUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemAPIServer).SaveUser(ctx, req.(*SaveUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemAPI_CheckAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemAPIServer).CheckAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/donech.erp.v1.SystemAPI/CheckAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemAPIServer).CheckAccount(ctx, req.(*CheckAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemAPI_Users_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemAPIServer).Users(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/donech.erp.v1.SystemAPI/Users",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemAPIServer).Users(ctx, req.(*UsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SystemAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "donech.erp.v1.SystemAPI",
	HandlerType: (*SystemAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveUser",
			Handler:    _SystemAPI_SaveUser_Handler,
		},
		{
			MethodName: "CheckAccount",
			Handler:    _SystemAPI_CheckAccount_Handler,
		},
		{
			MethodName: "Users",
			Handler:    _SystemAPI_Users_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "donech/erp/v1/system_api.proto",
}
